sudo: false

language: python

services:
  - postgresql

env:
  global:
    - DATABASE_URL='postgres://postgres:@localhost:5432/test_db'
    - SECRET_KEY='tT\xd7\xb06\xf7\x9b\xff\x0fZL\xca\xca\x11\xefM\xacr\xfb\xdf\xca\x9b'
    - DJANGO_SETTINGS_MODULE=core.settings.test_travis
    - RABBITMQ_HOST = 'rabbitmq'

python:
  - '3.4.5'

node_js:
  - "0.10"

addons:
  postgresql: "9.3"

services:
  - elasticsearch

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - pip install coveralls
  - pip install -r REQUIREMENTS-dev.txt
  - nodeenv -p --node=0.10.31
  - npm -g install yuglify
  - pip install git+https://github.com/django-haystack/django-haystack


before_script:
  - psql -c 'create database test_db;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test_db
  - npm install

script:
  # - flake8 --config .flake8 django_project
  - cd django_project
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run manage.py test
  - node_modules/karma/bin/karma start karma.conf.js --single-run

after_success:
  - coveralls

